version: "3.3"

services:
  product-lambda-app:
    container_name: product-lambda
    image: mdmago/product-lambda:dev
    volumes:
      - product-lambda-volume:/data
    networks:
      - microsservices
    restart: always
    env_file:
      - ./.env
    ports:
      - 5050:80


volumes:
  product-lambda-volume: {}

networks:
  microsservices: {}