version: "3.3"

services:
  product-app:
    container_name: product
    image: mdmago/product:dev
    volumes:
      - product-volume:/data
    networks:
      - microsservices
    env_file:
      - ./.env
    ports:
      - 5030:80

volumes:
  product-volume: {}

networks:
  microsservices: {}